import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

import { SidebarProvider } from "~/components/ui/sidebar";
import { AdminSidebar } from "~/components/AdminSidebar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <Toaster />
          <div className="flex flex-row h-screen">
            <SidebarProvider>
              <AdminSidebar /> 
                {children}
              {/* <div className="p-6 w-full h-full">
                <div className="rounded-3xl bg-white w-full h-full">
                </div>
              </div> */}
            </SidebarProvider>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
