name: aautad_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  go_router: ^14.8.0
  http: ^1.3.0
  jwt_decoder: ^2.0.1
  app_links: ^3.4.5
  uuid: ^4.5.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/cartao_socio_final.svg
    - lib/assets/fonts/
    - lib/assets/icons/
    - lib/assets/icons/logo.svg

  fonts:
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato-Regular.ttf
        - asset: lib/assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
